### ISSUE TITLE
Failed to estimate gas: message execution failed: exit 33, revert reason: Error(Not an evaluator)

### ISSUE THREAD

**Issue by bajtos** [filecoin-station/spark-evaluate#21]
When the evaluation service tries to submit evaluations, the ETH RPC call fails with the following error:

```
error: Error: processing response error (body="{\"jsonrpc\":\"2.0\",\"id\":3090,\"error\":{\"code\":1,\"message\":\"failed to estimate gas: message execution failed: exit 33, revert reason: Error(Not an evaluator), vm error: message failed with backtrace:\\n00: f037898 (method 3844450837) -- contract reverted (33)\\n (RetCode=33)\"}}\n", error={"code":1}, requestBody="{\"method\":\"eth_estimateGas\",\"params\":[{\"type\":\"0x2\",\"maxFeePerGas\":\"0x59682fc8\",\"maxPriorityFeePerGas\":\"0x59682f00\",\"from\":\"0xb0a808b5c49f5ed7af9ecaaaf033b2d937692877\",\"to\":\"0x381b50e8062757c404dec2bfae4da1b495341af9\",\"data\":\"0x9492c97c0000000000000000000000000000000000000000000000000000000000000145000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000f100ac342b7de48e5c89f7029624ee6c3cde68ac000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000038d7ea4c68000000000000000000000000000000000000000000000000000000000000000000e3432302072657472696576616c73000000000000000000000000000000000000\"}],\"id\":3090,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="https://api.calibration.node.glif.io/rpc/v0", code=SERVER_ERROR, version=web/5.7.1)
at Logger.makeError (/app/node_modules/@ethersproject/logger/lib/index.js:238:21)
at Logger.throwError (/app/node_modules/@ethersproject/logger/lib/index.js:247:20)
at /app/node_modules/@ethersproject/web/lib/index.js:313:32
at step (/app/node_modules/@ethersproject/web/lib/index.js:33:23)
at Object.next (/app/node_modules/@ethersproject/web/lib/index.js:14:53)
at fulfilled (/app/node_modules/@ethersproject/web/lib/index.js:5:58)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
reason: 'processing response error',
code: 'SERVER_ERROR',
body: '{"jsonrpc":"2.0","id":3090,"error":{"code":1,"message":"failed to estimate gas: message execution failed: exit 33, revert reason: Error(Not an evaluator), vm error: message failed with backtrace:\\n00: f037898 (method 3844450837) -- contract reverted (33)\\n (RetCode=33)"}}\n',
error: [Error],
requestBody: '{"method":"eth_estimateGas","params":[{"type":"0x2","maxFeePerGas":"0x59682fc8","maxPriorityFeePerGas":"0x59682f00","from":"0xb0a808b5c49f5ed7af9ecaaaf033b2d937692877","to":"0x381b50e8062757c404dec2bfae4da1b495341af9","data":"0x9492c97c0000000000000000000000000000000000000000000000000000000000000145000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000f100ac342b7de48e5c89f7029624ee6c3cde68ac000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000038d7ea4c68000000000000000000000000000000000000000000000000000000000000000000e3432302072657472696576616c73000000000000000000000000000000000000"}],"id":3090,"jsonrpc":"2.0"}',
requestMethod: 'POST',
url: 'https://api.calibration.node.glif.io/rpc/v0'
}
},
tx: {
data: '0x9492c97c0000000000000000000000000000000000000000000000000000000000000145000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000f100ac342b7de48e5c89f7029624ee6c3cde68ac000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000038d7ea4c68000000000000000000000000000000000000000000000000000000000000000000e3432302072657472696576616c73000000000000000000000000000000000000',
to: Promise { '0x381b50E8062757C404Dec2BfaE4Da1b495341Af9' },
from: '0xB0a808b5C49f5Ed7Af9EcAAaF033B2d937692877',
type: 2,
maxFeePerGas: BigNumber { _hex: '0x59682fc8', _isBigNumber: true },
maxPriorityFeePerGas: BigNumber { _hex: '0x59682f00', _isBigNumber: true },
nonce: Promise { 515 },
gasLimit: Promise { <rejected> [Circular *1] },
chainId: Promise { 314159 }
}
}
```

**Comment by juliangruber** [comment]
Added the missing role
